### ISSUE TITLE
feasibility of buffering multiple volumes

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/volume-viewer#102]
## Use Case

it would be great to be able to do real time playback of time series data but buffering multiple volumes is memory intensive. 

Can we detect anything about a user's system resources (cpu and/or gpu) and provide some automatic buffering capability?  
Can we allow power users some control over pre-buffering many times in a time series?

## Solution

Prototype ui widgets to let user say how many times to prebuffer.  Include some indicator of buffering progress and range of times in the buffer (say times 30-60 out of a 0-500 range).
Determine what things we can measure about a user's system resources from in-browser.

**Comment by toloudis** [comment]
Requirements for a good caching system for these images:
- bounded size
-- but could be adaptive based on auto detection of memory
-- or a build-time configuration setting
-- or a user setting
- fetch and cache times around the current time.  users are most likely to advance in time in this way.
- if user jumps far away from cached values, we need to potentially discard existing, cancel anything in-flight, and begin requesting around the new current time
- we are assuming whole multichannel volumes but this could also apply to single slices or other data types.

**Comment by toloudis** [comment]
`performance.memory` api available in chrome and edge but not firefox nor safari

**Comment by frasercl** [comment]
We can play through time now! It works ok!
