### ISSUE TITLE
combine mesh and volume rendering

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/volume-viewer#106]
## Use Case

Viewer supports concurrent display of volume and isosurface mesh but the rendering is not accurate.  We wish to be able to render both in a more accurate way. This is a key piece to have solved before merging volume rendering into simularium viewer. 

## Solution

Meshes render first, into depth buffer.  Volume shader reads from depth buffer once at each fragment and uses the value to modify the termination of the ray march if a mesh has a depth value that would be inside the volume.  In this concept, the mesh surface blocks the volume completely.

**Comment by frasercl** [comment]
transparency makes everything really hard

**Comment by toloudis** [comment]
The only implementation we need right now is the one for opaque meshes drawn into the depth buffer to terminate the ray marching.  
The key technical thing is to just get the depth values correct so that they can be compared against the ray positions.
Transparency is significantly more complex and might just have to settle for the current existing blending that we have.
