### ISSUE TITLE
Custom rendering for XY mode Pt. II

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/volume-viewer#114]
## Use Case

- Remove dependency on atlas subregion from RayMarchVolumeRendering
- Integrate with new slice cache (#110 + #112)

## Solution

- Draws a texture which contains the whole slice
- Details TBD once other components implemented

**Comment by toloudis** [comment]
I believe this task is really:
 "use single slice data storage to render in XY mode, rather than rendering from volume atlas"
 Prefetching is out of scope and will be a different ticket...

**Comment by toloudis** [comment]
What do we do if the data was not loaded as zarr?  (atlas.json or tiff?)

**Comment by frasercl** [comment]
Closed by #139
