### ISSUE TITLE
refactor VolumeRenderImpl classes

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/volume-viewer#123]
## Use Case

All VolumeRenderImpls should be considered independent and separate ways of drawing a volume.  Interface inheritance = good, implementation inheritance = less good.  Favor looser coupling between unrelated components.

## Solution

A followup change to https://github.com/allen-cell-animated/volume-viewer/pull/122

Atlas2DSlice should not inherit anything from RayMarchedAtlasVolume.  We can consider them completely separate ways for a VolumeDrawable to do its rendering.  This way if we need to change one or the other in the future, we won't have to worry that we are affecting both. 

It was also discussed that there may be some encapsulation of the settings that VolumeDrawable holds on to, that it can pass down to its VolumeRenderImpls for them to access.  Having such a third object (e.g. VolumeRenderSettings?) would also break a potential circular dependency where the code just passes the who VolumeDrawable itself down into its owned VolumeRenderImpls.
Ultimately, the VolumeDrawable may boil down to a VolumeRenderImpl, VolumeRenderSettings, and some logic about how to switch between different VolumeRenderImpls.   This is slightly speculative and not a strict specification to adhere to.

**Comment by ShrimpCryptid** [comment]
https://github.com/allen-cell-animated/volume-viewer/pull/124

**Comment by ShrimpCryptid** [comment]
Splitting the settings fix into a separate issue!
