### ISSUE TITLE
RequestQueue test occasionally fails

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/volume-viewer#128]
## Description

![image](https://github.com/allen-cell-animated/volume-viewer/assets/30200665/1be3c465-80d5-4bf5-aa5f-d053cb68a212)

Likely some incorrect async behavior assumption. Occasionally causes the tests to fail, but resolves after tests are re-run.

**Comment by toloudis** [comment]
is this related to some hardcoded time in the test not waiting long enough for things to finish?

**Comment by ShrimpCryptid** [comment]
```
    it("can issue delayed requests", async () => {
      const rq = new RequestQueue();
      const startTime = Date.now();
      const delayMs = 15;
      const immediatePromise = rq.addRequest("a", async () => {return;});
      const delayedPromise = rq.addRequest("b", async () => {return;}, delayMs);

      const promises: Promise<unknown>[] = [];
      promises.push(immediatePromise.then(() => {
        expect(Date.now() - startTime).to.be.lessThan(delayMs);
      }));
      promises.push(delayedPromise.then(() => {
        expect(Date.now() - startTime).to.be.greaterThanOrEqual(delayMs);  // error happens here
      }));
      await Promise.all(promises);
    });
```

Here's the offending code for reference. It looks like it's making a request with a delay of 15 ms, but the request is actually getting called sooner at 14 ms? It could also be a rounding error or something that's causing it, but probably the easiest solution is adding some amount of buffer/time tolerance I think

**Comment by ShrimpCryptid** [comment]
Fixed by adding a 1 ms buffer due to known timing inconsistency with setTimeout.
