### ISSUE TITLE
Rework `LoadSpec`

### ISSUE THREAD

**Issue by frasercl** [allen-cell-animated/volume-viewer#134]
## Use Case

As a developer, the `LoadSpec` type doesn't capture all settings that are relevant when loading a volume.

## Solution

- Remove the `subpath` field, replace with something like `resolutionLevel`
- Consider giving extent fields in pixels at provided resolution level, rather than 0-1 floats
- Add a list of channel indexes to load

**Comment by toloudis** [comment]
Consider refactor to remove url from LoadSpec and provide it to stateful IVolumeLoaders in ctor.  One goal being to help enforce that loadspecs can be the "original" load spec, and also a requested new loadspec that is intended to use the same data source.   So a possible alternative is to have two different flavors of LoadSpec.  LoadSpec and LoadSpecRequest? or even LoadSpec and LoadSpecWithUrl!
