### ISSUE TITLE
Don't rebuild tweakpane unless it is open

### ISSUE THREAD

**Issue by frasercl** [allen-cell-animated/volume-viewer#156]
## Description

A significant portion of the work done on volume load is related to Tweakpane, which most users will never open. Now that we expect to do lots of volume loads, it's worth making that process fast.

## Expected Behavior

Tweakpane should not take up so much time on volume loads if it isn't being used.

## Reproduction

Switch to a time series volume, start recording in the devtools profiler, move the time slider, and check out how much load time is taken up by Tweakpane.

**Comment by toloudis** [comment]
May also fix #143
