### ISSUE TITLE
handle zarrs that are too big

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/volume-viewer#174]
## Use Case

Accounting for all multiresolution levels, if:
* 2D mode: zarr has data in which a single slice is larger than our texture size
* 3D mode: zarr has data in which the XYZ dimensions do not tile into our preferred texture size

then we either have to error out in some way or downsample in the viewer

## Solution

Error out gracefully - perhaps find a way to propagate error out to clients, even if it's just `throw new Error("Zarr too big")`

## Alternatives
1. show some cropped subset of the data which is easy to display quickly.
2. Downsample on the fly.  Has performance concerns naively downsampling potentially very large data.  Potentially fraught with other details to deal with.

**Comment by ShrimpCryptid** [comment]
May be dependent on https://github.com/allen-cell-animated/website-3d-cell-viewer/issues/183.
