### ISSUE TITLE
remove redundant imageinfo fields

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/volume-viewer#251]
## Use Case

From @frasercl :
So it's in writing which fields are specifically redundant: volumeSize, numChannels, and times should now be derivable from multiscaleLevelDims and multiscaleLevel (which I actually kind of like better). and originalSize might just be multiscaleLevelDims[0].shape depending on whether level 0 is always considered the "original" (currently not the case with JSON vols, and maybe not with ZARR either)

## Solution

remove redundancies in ImageInfo

**Comment by frasercl** [comment]
Original comment from #226
