### ISSUE TITLE
Upper bound of `Uint8Array` size in `setChannelDataFromVolume`

### ISSUE THREAD

**Issue by antonysigma** [allen-cell-animated/volume-viewer#256]
Hi I enjoy using the volume viewer in my web GUI project. Thank you for the great work!

I am trying to stream a raw volume of size `1024 x 1024 x 64` times 3 channels into the viewer. The raw data has type `Uint8Array`. However, when I run the volume viewer on the Chrome browser, it can only accept up to `128 x 128 x 64`. I get an error for larger size:

```javascript
runtime-core.esm-bundler.js:275 RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8ClampedArray (<anonymous>)
    at qs.packToAtlas (Channel.js:175:13)
    at qs.setFromVolumeData (Channel.js:153:10)
    at Xs.setChannelDataFromVolume (Volume.js:294:33)
```

However, using the exact same Chrome browser and the same computer, this [demo](https://allen-cell-animated.github.io/volume-viewer/) appears to show a much larger volume than what I have. I am wondering what makes the demo work on larger sized volume?

I attached the screenshot of the official demo here:
![image](https://github.com/user-attachments/assets/1b99b29a-d045-4c2b-937e-1af958537bb6)

Another question: if it true that `atlas.json` and atlas PNGs is far more memory efficient than `Uint8Array`? If so, where can I read the specification? I am implementing my own `Uint8Array` web server, but I can refactor the code to generate and serve `atlas.json` and atlas tiled PNGs on demand.

Related issues: #216 , #67, #171 .

**Comment by toloudis** [comment]
Thanks for posting this!  We will give this a think and get back to you early next week...

At first glance, it looks like our RawArrayLoader still expects the array to fit into our gpu atlas constraints, which is that all slices must fit tiled into a 4k texture.  So you probably need to downsample before handing the data to the viewer.
There's an advanced setting that lets you increase that limit.

**Comment by antonysigma** [comment]
Thank you for the insights. Here the minimal reproducible code that triggers the memory allocation failure on the web browser:

```typescript

// Works on Chrome browser when N <= 128.
const N = 256;
const Z = 64;
const volume_metadata: ImageInfo = {
    ...getDefaultImageInfo(),
    ...{
        name: "My volume",
        originalSize: new Vector3(N, N, Z),
        atlasTileDims: new Vector2(N, N),
        volumeSize: new Vector3(N, N, Z),
        physicalPixelSize: new Vector3(0.5, 0.5, 0.5),
        subregionSize: new Vector3(N, N, Z),
        spatialUnit: "um",
        numChannels: 0,
        channelNames: ["CH0"],
        channelColors: [
            [255.0, 255.0, 255.0],
        ],
    },
};

const volume = new Volume(volume_metadata);
{
    const height = Z;
    const radius = N * 0.3;
    const cone = VolumeMaker.createCone(N, N, Z, height, radius);
    volume.setChannelDataFromVolume(1, cone, [0, 255]);
}

const view_3d = new View3d(document.getElementById('volume-viewer'));
view_3d.addVolume(volume);

view_3d.setVolumeChannelEnabled(volume, 0, true);
```

**Comment by antonysigma** [comment]
Update: It turns out I overestimated the `atlasTileDims` parameter. It should be `new Vector2(sqrt(z_plane_count), sqrt(z_plane_count))`. Previously, I put a value of `[1024, 1024]` causing the web browser to run out of memory.

Closing this issue...

**Comment by toloudis** [comment]
> Update: It turns out I overestimated the `atlasTileDims` parameter. It should be `new Vector2(sqrt(z_plane_count), sqrt(z_plane_count))`. Previously, I put a value of `[1024, 1024]` causing the web browser to run out of memory.
> 
> Closing this issue...

Thanks for the update, good to know it was just a bad parameter value.   Documentation is high on our list right now.  As you figured out, atlasTileDims is supposed to be the number of tiles  (z slices) to fit in a big 2D texture that we allocate.  Arguably this is an implementation detail which should not be leaking out.  It is originally there for a good reason, decoding volumetric data that was packed into 2d image files.
