### ISSUE TITLE
max project mode is too dark compared to raymarch mode

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/volume-viewer#53]
## Description

When switching from regular raymarch volume rendering to max-project mode, the max projection mode often is too dark to see anything.

## Expected Behavior

Max project mode with same density and brightness settings should appear similar in color and brightness to the raymarch mode.

**Comment by frasercl** [comment]
Closed by #72, but leaving in "In Review" on the [project board](https://github.com/orgs/allen-cell-animated/projects/5) until Graham et al. can experiment and offer input.

**Comment by frasercl** [comment]
Graham's feedback, briefly:
- "mask cell" default value should be 85% - something to consider, but not a huge issue
- unclear what max project ought to do in 2d modes - captured by allen-cell-animated/website-3d-cell-viewer#87
- looks good - hooray!

There also remains the concern that max project mode no longer responds to levels, which may warrant its own issue. That said, I feel comfortable moving this to done.
