### ISSUE TITLE
better way to load test data

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/volume-viewer#81]
## Use Case

The collection of testable data urls for this demo app is just a bunch of commented-out lines hardcoded.  It looks ugly and you have to rebuild the code to change the test data.

## Solution

Add some ui to the demo app to let user select from preset data urls.  This could also help to inform efforts to build a data-loading gui

## Alternatives

Just clean up the code and make the data urls an array.

**Comment by frasercl** [comment]
Resolved by #88
