### ISSUE TITLE
multiresolution in 2d mode

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/volume-viewer#91]
## Use Case

When viewing a single slice, the viewer could support higher resolution data.  This would provide a more detailed and accurate view of 2d slices of z-stacks for users.

## Solution

Zarr is the best example of precomputed multiresolution data.   We have the opportunity to use a fixed size cache of full-res (up to some practical limit) tiles of individual slices.   3D mode would still use the same data structure it uses now but 2D could use higher res slices.  We can investigate google maps-like dynamic loading when zooming, taking viewport dimensions into account, or even something like OpenSeaDragon to present 2d.

Min requirement is to let single slice viewing use higher resolutions.

**Comment by toloudis** [comment]
also see #115

**Comment by frasercl** [comment]
We did this! In #163
